/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package prog2.vista;

import javax.swing.JOptionPane;
import adaptador.Adaptador;

/**
 *
 * @author Javier Rivera Romeu
 */

public class GestionComponentes extends javax.swing.JDialog {
    private CentralUB central;
    private Adaptador adaptador;
    // Creates new form GestionComponentes
    public GestionComponentes(java.awt.Frame parent, boolean modal, CentralUB central) {
        super(parent, modal);
        this.central = central;
        this.adaptador = central.getAdaptador(); 
        initComponents();
        inicializarComponentes(); //Para que se actualize su valor y podamos conocerlo. 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        SliderBarras = new javax.swing.JSlider();
        MensajeBarras = new javax.swing.JLabel();
        BarrasTexto = new javax.swing.JTextField();
        BotonTextoBarras = new javax.swing.JButton();
        MensajeActivar = new javax.swing.JLabel();
        ActivarReactorBoton = new javax.swing.JButton();
        DesactivarReactorBoton = new javax.swing.JButton();
        MensajeBombas = new javax.swing.JLabel();
        BombaUno = new javax.swing.JRadioButton();
        BombaDos = new javax.swing.JRadioButton();
        BombaCuatro = new javax.swing.JRadioButton();
        BombaTres = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SliderBarras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderBarrasStateChanged(evt);
            }
        });

        MensajeBarras.setText("Introduzca el PORCENTAJE de INSERCCIÓN");

        BarrasTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarrasTextoActionPerformed(evt);
            }
        });

        BotonTextoBarras.setText("Modificar");
        BotonTextoBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTextoBarrasActionPerformed(evt);
            }
        });

        MensajeActivar.setText("ACTIVE/DESACTIVE el REACTOR");

        ActivarReactorBoton.setText("Activar");
        ActivarReactorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActivarReactorBotonActionPerformed(evt);
            }
        });

        DesactivarReactorBoton.setText("Desactivar");
        DesactivarReactorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesactivarReactorBotonActionPerformed(evt);
            }
        });

        MensajeBombas.setText("Seleccione aquellas BOMBAS que desee ACTIVAR");

        BombaUno.setText("Bomba I ");
        BombaUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BombaUnoActionPerformed(evt);
            }
        });

        BombaDos.setText("Bomba II");
        BombaDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BombaDosActionPerformed(evt);
            }
        });

        BombaCuatro.setText("Bomba IV ");
        BombaCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BombaCuatroActionPerformed(evt);
            }
        });

        BombaTres.setText("Bomba III");
        BombaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BombaTresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SliderBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BarrasTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonTextoBarras))
                    .addComponent(MensajeBarras)
                    .addComponent(MensajeActivar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ActivarReactorBoton)
                        .addGap(18, 18, 18)
                        .addComponent(DesactivarReactorBoton))
                    .addComponent(MensajeBombas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BombaUno)
                        .addGap(18, 18, 18)
                        .addComponent(BombaTres))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BombaDos)
                        .addGap(18, 18, 18)
                        .addComponent(BombaCuatro)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(MensajeBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SliderBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarrasTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTextoBarras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeActivar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActivarReactorBoton)
                    .addComponent(DesactivarReactorBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MensajeBombas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BombaUno)
                    .addComponent(BombaTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BombaDos)
                    .addComponent(BombaCuatro))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BarrasTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarrasTextoActionPerformed
    // Obtenemos el valor del campo de texto
    String valorTexto = BarrasTexto.getText();
    try {
        // Convertimos el valor a entero y lo establecemos en el JSlider
        int valor = Integer.parseInt(valorTexto);
        SliderBarras.setValue(valor);
        adaptador.setInsercioBarres(valor);
    } catch (NumberFormatException e) {
        // En caso de error al convertir, mostramos un mensaje de error
        JOptionPane.showMessageDialog(this, "Por favor, introduce un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (CentralUBException e) {
        JOptionPane.showMessageDialog(this, "Error al aplicar el valor de inserción de barras: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BarrasTextoActionPerformed

    private void BotonTextoBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTextoBarrasActionPerformed
    // Obtenemos el valor del campo de texto
    String valorTexto = BarrasTexto.getText();
    try {
        // Convertimos el valor a entero y lo establecemos en el JSlider
        int valor = Integer.parseInt(valorTexto);
        SliderBarras.setValue(valor);
        adaptador.setInsercioBarres(valor);
    } catch (NumberFormatException e) {
        // En caso de error al convertir, mostramos un mensaje de error
        JOptionPane.showMessageDialog(this, "Por favor, introduce un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (CentralUBException e) {
        JOptionPane.showMessageDialog(this, "Error al aplicar el valor de inserción de barras: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BotonTextoBarrasActionPerformed

    private void ActivarReactorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActivarReactorBotonActionPerformed
    try {
        adaptador.activaReactor();
        JOptionPane.showMessageDialog(this, "Reactor activado correctamente.", "Reactor Activado", JOptionPane.INFORMATION_MESSAGE);
    } catch (CentralUBException e) {
        JOptionPane.showMessageDialog(this, "Error al activar el reactor: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ActivarReactorBotonActionPerformed

    private void BombaUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BombaUnoActionPerformed
    if (BombaUno.isSelected()) {
        try {
            adaptador.activaBomba(0);
            JOptionPane.showMessageDialog(this, "Bomba I activada correctamente.", "Bomba Activada", JOptionPane.INFORMATION_MESSAGE);
        } catch (CentralUBException e) {
            JOptionPane.showMessageDialog(this, "Error al activar la Bomba I: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            BombaUno.setSelected(false);
        }
    } else {
        adaptador.desactivaBomba(0);
        JOptionPane.showMessageDialog(this, "Bomba I desactivada correctamente.", "Bomba Desactivada", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BombaUnoActionPerformed

    private void BombaDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BombaDosActionPerformed
    if (BombaDos.isSelected()) {
        try {
            adaptador.activaBomba(1);
            JOptionPane.showMessageDialog(this, "Bomba II activada correctamente.", "Bomba Activada", JOptionPane.INFORMATION_MESSAGE);
        } catch (CentralUBException e) {
            JOptionPane.showMessageDialog(this, "Error al activar la Bomba II: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            BombaDos.setSelected(false);
        }
    } else {
        adaptador.desactivaBomba(1);
        JOptionPane.showMessageDialog(this, "Bomba II desactivada correctamente.", "Bomba Desactivada", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BombaDosActionPerformed

    private void BombaCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BombaCuatroActionPerformed
    if (BombaCuatro.isSelected()) {
        try {
            adaptador.activaBomba(3);
            JOptionPane.showMessageDialog(this, "Bomba IV activada correctamente.", "Bomba Activada", JOptionPane.INFORMATION_MESSAGE);
        } catch (CentralUBException e) {
            JOptionPane.showMessageDialog(this, "Error al activar la Bomba IV: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            BombaCuatro.setSelected(false);
        }
    } else {
        adaptador.desactivaBomba(3);
        JOptionPane.showMessageDialog(this, "Bomba IV desactivada correctamente.", "Bomba Desactivada", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BombaCuatroActionPerformed

    private void BombaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BombaTresActionPerformed
    if (BombaTres.isSelected()) {
        try {
            adaptador.activaBomba(2);
            JOptionPane.showMessageDialog(this, "Bomba III activada correctamente.", "Bomba Activada", JOptionPane.INFORMATION_MESSAGE);
        } catch (CentralUBException e) {
            JOptionPane.showMessageDialog(this, "Error al activar la Bomba III: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            BombaTres.setSelected(false);
        }
    } else {
        adaptador.desactivaBomba(2);
        JOptionPane.showMessageDialog(this, "Bomba III desactivada correctamente.", "Bomba Desactivada", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_BombaTresActionPerformed

    private void DesactivarReactorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesactivarReactorBotonActionPerformed
        adaptador.desactivaReactor();
        JOptionPane.showMessageDialog(this, "Reactor desactivado correctamente.", "Reactor Desactivado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_DesactivarReactorBotonActionPerformed

    private void SliderBarrasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderBarrasStateChanged
    // Actualizar el campo de texto con el valor del slider
    int valor = SliderBarras.getValue();
    BarrasTexto.setText(String.valueOf(valor));
    try {
        adaptador.setInsercioBarres(valor);
    } catch (CentralUBException e) {
        JOptionPane.showMessageDialog(this, "Error al aplicar el valor de inserción de barras: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SliderBarrasStateChanged
    // Método para inicializar los valores de los componentes
    private void inicializarComponentes() {
        // Inicializar el valor del slider y el campo de texto con la inserción de barras actual
        float insercioBarres = adaptador.getInsercioBarres();
        SliderBarras.setValue((int) insercioBarres);
        BarrasTexto.setText(String.valueOf(insercioBarres));
        // Inicializar los botones de las bombas con su estado actual
        BombaUno.setSelected(adaptador.isBombaActiva(0));
        BombaDos.setSelected(adaptador.isBombaActiva(1));
        BombaTres.setSelected(adaptador.isBombaActiva(2));
        BombaCuatro.setSelected(adaptador.isBombaActiva(3));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionComponentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CentralUB central = new CentralUB();
                GestionComponentes dialog = new GestionComponentes(new javax.swing.JFrame(), true, central);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActivarReactorBoton;
    private javax.swing.JTextField BarrasTexto;
    private javax.swing.JRadioButton BombaCuatro;
    private javax.swing.JRadioButton BombaDos;
    private javax.swing.JRadioButton BombaTres;
    private javax.swing.JRadioButton BombaUno;
    private javax.swing.JButton BotonTextoBarras;
    private javax.swing.JButton DesactivarReactorBoton;
    private javax.swing.JLabel MensajeActivar;
    private javax.swing.JLabel MensajeBarras;
    private javax.swing.JLabel MensajeBombas;
    private javax.swing.JSlider SliderBarras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    // End of variables declaration//GEN-END:variables

}
